name: test-if-statement-step
description: Testen van if statement in je step

inputs:
  zoektekst:
    description: Specifieke zoektekst om te zoeken in de testzoek
    default: Peridos
    required: true
  tekstzoek:
    description: Zoek de zoektekst in deze testzoek ;D
    default: ""
    required: true

runs:
  using: "composite"
  steps:
    - name: Wel gevonden
      if: contains(inputs.tekstzoek, inputs.zoektekst)
      run: echo ja de zoek is succesvol
      shell: bash
    - name: Niet gevonden
      if: !contains(inputs.tekstzoek, inputs.zoektekst)
      run: echo de zoek is onsuccesvol
      shell: bash
