name: octo-deploy-release-mock
description: Mock van octo deploy release

inputs:
  screenit_of_peridos:
    description: Is dit voor peridos of screenit
    default: Peridos
    required: true
  omgeving:
    description: De omgeving waar je naar wilt deployen
    default: ""
    required: true
  runbook_naam:
    description: Naam van de runbook die getriggered wordt


runs:
  using: "composite"
  steps:
    - name: deploying-release
      run: |
        echo "deploying runbook op ${{ inputs.omgeving }} voor ${{ inputs.screenit_of_peridos }}, runbooknaam = ${{ inputs.runbook_naam }}"
      shell: bash
