name: deploy-omgeving
description: Bepaalt variabelen en trapt workflows af.

inputs:
  deploy_string:
    description: String die meegegeven wordt vanuit workflow, bevat alle omgevingen die gedeployed moeten worden
    required: true
  screenit_of_peridos:
    description: Is dit voor peridos of screenit
    default: Peridos
    required: true
  runbook_of_release:
    description: Runbook of release
    default: ""
    required: true
  omgeving:
    description: De omgeving waar je naar wilt deployen
    default: ""
    required: true
  runbook_naam:
    description: Runbook naam die je wilt starten
    default: ""
    required: true
  zoek_string_voor_omgeving:
    description: String waar de action naar zoekt om te bepalen of die moet deployen
    default: ""
    required: true
runs:
  using: "composite"
  steps:
   - run: |
      echo "test"
      echo "deploy_string ${{inputs.deploy_string}}"
      echo "omgeving ${{inputs.omgeving}}"
      echo "runbook_naam ${{inputs.runbook_naam}}"
      echo "runbook_of_release ${{inputs.runbook_of_release}}"
      echo "screenit_of_peridos ${{inputs.screenit_of_peridos}}"
      echo "zoek_string_voor_omgeving ${{inputs.zoek_string_voor_omgeving}}"
      gh workflow run --help
     shell: bash